server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /health {
    return 200 'ok';
    add_header Content-Type text/plain;
  }

  # Cache assets statiques
  location ~* \.(css|js|png|svg|jpg|jpeg|webp|woff2?)$ {
    expires 30d;
    add_header Cache-Control "public, immutable";
  }
}
